name: rabpro
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7,<3.10
  - gdal
  - numpy
  - geopandas
  - scikit-image  
  - pyproj>2.2.0
  - shapely
  - requests
  - appdirs
  - earthengine-api
  - gdown
  - tqdm
  - beautifulsoup4
